# Generated by Django 3.2.11 on 2022-02-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='note',
            field=models.CharField(blank=True, default=None, help_text='补充说明', max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='semesterconfig',
            name='max_week',
            field=models.IntegerField(default=20, help_text='本学期共计多少周', verbose_name='最大周数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='这条记录的更新时间', verbose_name='更新时间'),
        ),
    ]
