# Generated by Django 3.2.11 on 2022-03-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='method',
            field=models.CharField(choices=[('Course', '理论课'), ('TD', '习题课'), ('TP', '实验课'), ('Exam', '考试')], default='Course', help_text='Course/TD/TP/Exam', max_length=8, verbose_name='授课方式'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.ForeignKey(blank=True, help_text='FK-Classroom', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_course', to='course.classroom', verbose_name='教室'),
        ),
        migrations.AlterField(
            model_name='coursechangelog',
            name='method',
            field=models.CharField(choices=[('Course', '理论课'), ('TD', '习题课'), ('TP', '实验课'), ('Exam', '考试')], default='Course', help_text='Course/TD/TP/Exam', max_length=8, verbose_name='授课方式'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='method',
            field=models.CharField(choices=[('Course', '理论课'), ('TD', '习题课'), ('TP', '实验课'), ('Exam', '考试')], help_text='Course/TD/TP/Exam', max_length=8, verbose_name='授课方式'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='FK-Teacher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_plan', to='course.teacher', verbose_name='授课教师'),
        ),
    ]
