# Generated by Django 3.2.8 on 2022-01-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='教室名', max_length=100, unique=True, verbose_name='教室名'),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(help_text='这节课的上课日期', verbose_name='这节课的上课日期'),
        ),
        migrations.AlterField(
            model_name='course',
            name='plan',
            field=models.ForeignKey(help_text='FK-CoursePlan', on_delete=django.db.models.deletion.CASCADE, related_name='plan_course', to='course.courseplan', verbose_name='教学计划'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.ForeignKey(help_text='FK-Classroom', on_delete=django.db.models.deletion.CASCADE, related_name='room_course', to='course.classroom', verbose_name='教室'),
        ),
        migrations.AlterField(
            model_name='course',
            name='which_lesson',
            field=models.CharField(choices=[('1', '第1,2节课'), ('2', '第3,4节课'), ('3', '第5,6节课'), ('4', '第7,8节课'), ('5', '第9,10节课')], help_text='第?节课，∈[1,5]', max_length=8, verbose_name='第?节课'),
        ),
        migrations.AlterField(
            model_name='coursechangelog',
            name='action',
            field=models.CharField(choices=[('Create', '新增'), ('Update', '更新'), ('Delete', '删除')], help_text='新增/更新/删除', max_length=8, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='coursechangelog',
            name='description',
            field=models.CharField(blank=True, help_text='对本次变动的描述', max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='coursechangelog',
            name='plan',
            field=models.ForeignKey(help_text='FK-CoursePlan', on_delete=django.db.models.deletion.CASCADE, related_name='plan_log', to='course.courseplan', verbose_name='教学计划'),
        ),
        migrations.AlterField(
            model_name='coursechangelog',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, help_text='该变动发生的时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='ch_name',
            field=models.CharField(help_text='课程中文名', max_length=100, unique=True, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='en_name',
            field=models.CharField(blank=True, help_text='课程英语名', max_length=100, null=True, verbose_name='English'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='fr_name',
            field=models.CharField(blank=True, help_text='课程法语名', max_length=100, null=True, verbose_name='Français'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='period',
            field=models.IntegerField(help_text='从2007.9算起的第?学期', verbose_name='时期'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='semester',
            field=models.CharField(choices=[('1', '大一上'), ('2', '大一下'), ('3', '大二上'), ('4', '大二下'), ('5', '大三上'), ('6', '大三下'), ('7', 'S1'), ('8', 'S2'), ('9', 'S3'), ('10', 'S4'), ('11', 'S5'), ('12', 'S6'), ('13', 'S7'), ('14', 'S8')], help_text='从大一上算起的第?学期 ∈ [1,14]', max_length=8, verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='type',
            field=models.ForeignKey(help_text='FK-CourseType', on_delete=django.db.models.deletion.CASCADE, related_name='type_info', to='course.coursetype', verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='groups',
            field=models.ManyToManyField(help_text='M2M Plan&Group', related_name='group_plan', to='course.Group', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='info',
            field=models.ForeignKey(help_text='FK-CourseInfo', on_delete=django.db.models.deletion.CASCADE, related_name='info_plan', to='course.courseinfo', verbose_name='课程信息'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='method',
            field=models.CharField(choices=[('理论课', 'Course'), ('习题课', 'TD'), ('实验课', 'TP'), ('考试', 'DS')], help_text='授课方式', max_length=8, verbose_name='授课方式'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='teacher',
            field=models.ForeignKey(help_text='FK-Teacher', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_plan', to='course.teacher', verbose_name='授课教师'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='color',
            field=models.CharField(help_text='颜色，六位字符，例如：FFFFFF', max_length=6, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(help_text='类型名', max_length=100, unique=True, verbose_name='类型名'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='分组名称，例如：PA', max_length=100, verbose_name='分组名称'),
        ),
        migrations.AlterField(
            model_name='group',
            name='period',
            field=models.IntegerField(help_text='从2007.9算起的第?学期', verbose_name='时期'),
        ),
        migrations.AlterField(
            model_name='group',
            name='semester',
            field=models.CharField(choices=[('1', '大一上'), ('2', '大一下'), ('3', '大二上'), ('4', '大二下'), ('5', '大三上'), ('6', '大三下'), ('7', 'S1'), ('8', 'S2'), ('9', 'S3'), ('10', 'S4'), ('11', 'S5'), ('12', 'S6'), ('13', 'S7'), ('14', 'S8')], help_text='从大一上算起的第?学期 ∈ [1,14]', max_length=8, verbose_name='学期'),
        ),
        migrations.AlterField(
            model_name='semesterconfig',
            name='current_period',
            field=models.IntegerField(help_text='从2007.9算起的第?学期', verbose_name='当前时期'),
        ),
        migrations.AlterField(
            model_name='semesterconfig',
            name='week1_monday_date',
            field=models.DateTimeField(help_text='本学期第一周星期一的日期', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(help_text='授课教师姓名', max_length=100, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='validity',
            field=models.BooleanField(default=True, help_text='是否参与当前教学计划', verbose_name='是否生效'),
        ),
    ]
