# Generated by Django 3.2.11 on 2022-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterconfig',
            name='week1_monday_date',
            field=models.DateTimeField(help_text='本学期第一周星期一的日期', verbose_name='学期开始日期'),
        ),
    ]
