# Generated by Django 3.2.11 on 2022-02-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220205_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_common',
            field=models.BooleanField(default=True, help_text='是否可作为自习室', verbose_name='是否自习室'),
        ),
    ]
