# Generated by Django 3.2.11 on 2022-03-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220308_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='color',
            field=models.CharField(blank=True, help_text='颜色，六位字符，例如：FFFFFF', max_length=6, null=True, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='授课教师姓名', max_length=100, null=True, unique=True, verbose_name='授课教师姓名'),
        ),
    ]
