# Generated by Django 3.2.11 on 2022-03-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20220308_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='授课教师姓名', max_length=100, null=True, verbose_name='授课教师姓名'),
        ),
    ]
