# Generated by Django 3.2.11 on 2022-02-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_classroom_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ch_name',
            field=models.CharField(blank=True, help_text='课程中文名', max_length=100, null=True, verbose_name='中文名'),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='', help_text='课程编号(如CS21,ES22)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(blank=True, help_text='颜色，六位字符，例如：FFFFFF', max_length=6, null=True, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='course',
            name='en_name',
            field=models.CharField(blank=True, help_text='课程英语名', max_length=100, null=True, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='course',
            name='fr_name',
            field=models.CharField(blank=True, help_text='课程法语名', max_length=100, null=True, verbose_name='Français'),
        ),
        migrations.AddField(
            model_name='course',
            name='group_ids',
            field=models.CharField(blank=True, help_text='group_id(s),以字符串储存列表', max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='course',
            name='method',
            field=models.CharField(choices=[('Course', '理论课'), ('TD', '习题课'), ('TP', '实验课'), ('DS', '考试')], default='Course', help_text='Course/TD/TP/DS', max_length=8, verbose_name='授课方式'),
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.IntegerField(blank=True, help_text='从2007.9算起的第?学期', null=True, verbose_name='时期'),
        ),
        migrations.AddField(
            model_name='course',
            name='room_name',
            field=models.CharField(blank=True, help_text='教室名', max_length=100, null=True, verbose_name='教室名'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, '大一上'), (2, '大一下'), (3, '大二上'), (4, '大二下'), (5, '大三上'), (6, '大三下'), (7, 'S1'), (8, 'S2'), (9, 'S3'), (10, 'S4'), (11, 'S5'), (12, 'S6'), (13, 'S7'), (14, 'S8')], help_text='从大一上算起的第?学期 ∈ [1,14]', null=True, verbose_name='学期'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='授课教师姓名', max_length=100, null=True, verbose_name='姓名'),
        ),
    ]
