# Generated by Django 3.2.11 on 2022-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_courseplan_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplan',
            name='ch_name',
            field=models.CharField(blank=True, help_text='课程中文名', max_length=100, null=True, verbose_name='中文名'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='code',
            field=models.CharField(blank=True, default='', help_text='课程编号(如CS21,ES22)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='color',
            field=models.CharField(blank=True, help_text='颜色，六位字符，例如：FFFFFF', max_length=6, null=True, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='en_name',
            field=models.CharField(blank=True, help_text='课程英语名', max_length=100, null=True, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='fr_name',
            field=models.CharField(blank=True, help_text='课程法语名', max_length=100, null=True, verbose_name='Français'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='period',
            field=models.IntegerField(blank=True, help_text='从2007.9算起的第?学期', null=True, verbose_name='时期'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, '大一上'), (2, '大一下'), (3, '大二上'), (4, '大二下'), (5, '大三上'), (6, '大三下'), (7, 'S1'), (8, 'S2'), (9, 'S3'), (10, 'S4'), (11, 'S5'), (12, 'S6'), (13, 'S7'), (14, 'S8')], help_text='从大一上算起的第?学期 ∈ [1,14]', null=True, verbose_name='学期'),
        ),
    ]
