# Generated by Django 3.2.11 on 2022-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220217_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('content', models.CharField(help_text='对本次变动的描述', max_length=255, verbose_name='描述')),
                ('link', models.TextField(blank=True, help_text='点击通知时跳转链接', null=True, verbose_name='链接')),
                ('validity', models.BooleanField(default=True, help_text='是否生效', verbose_name='是否生效')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='这条记录的更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
            },
        ),
    ]
