# Generated by Django 3.2.11 on 2022-03-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220316_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['plan', 'date', 'which_lesson'], 'verbose_name': '排课记录', 'verbose_name_plural': '排课记录'},
        ),
        migrations.AlterModelOptions(
            name='courseplan',
            options={'ordering': ('info', 'method'), 'verbose_name': '教学计划', 'verbose_name_plural': '教学计划'},
        ),
    ]
