# Generated by Django 3.2.11 on 2022-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220326_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='groups_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='分组名'),
        ),
        migrations.AddField(
            model_name='coursechangelog',
            name='groups_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='分组名'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='groups_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='分组名'),
        ),
    ]
