# Generated by Django 3.2.11 on 2022-05-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20220412_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='color',
            field=models.CharField(help_text='颜色，六位字符，例如：#FFFFFF', max_length=7, verbose_name='颜色'),
        ),
    ]
