# Generated by Django 3.2.11 on 2022-05-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_coursetype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(blank=True, help_text='颜色，例如：#FFFFFF', max_length=32, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='coursechangelog',
            name='color',
            field=models.CharField(blank=True, help_text='颜色，例如：#FFFFFF', max_length=32, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='color',
            field=models.CharField(blank=True, help_text='颜色，例如：#FFFFFF', max_length=32, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='color',
            field=models.CharField(blank=True, help_text='颜色，例如：#FFFFFF', max_length=32, null=True, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='color',
            field=models.CharField(help_text='颜色，例如：#FFFFFF', max_length=32, verbose_name='颜色'),
        ),
    ]
